# Generated by Django 2.2.3 on 2020-01-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Users_type', models.CharField(choices=[('Farmer', 'Farmer'), ('Buyer', 'Buyer')], default='F', max_length=1)),
                ('Phone_number', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=250)),
                ('field_area', models.IntegerField()),
            ],
        ),
    ]
