# Generated by Django 2.2.3 on 2020-01-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200120_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='field_area',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='id',
        ),
        migrations.AddField(
            model_name='farmer',
            name='Price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='farmer',
            name='Product',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='address',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='first_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='last_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='phone_number',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='Address',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='First_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='Last_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='Phone_number',
            field=models.CharField(default='None', max_length=10, primary_key=True, serialize=False),
        ),
    ]
